<!DOCTYPE html>
<html lang="en-gb">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 2.4.0">
  <meta name="generator" content="Hugo 0.59.0" />
  <meta name="author" content="Amalan Mahendran">

  
  
  
  
    
  
  <meta name="description" content="2019 Week 2 TidyTuesday: Imdb Tv Shows.">

  
  <link rel="alternate" hreflang="en-gb" href="/post/tidytuesday2019/week-2-imdb-tv-shows-data/">

  


  

  

  

  
  
  
  <meta name="theme-color" content="#3D3B45">
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" integrity="sha256-ygkqlh3CYSUri3LhQxzdcm0n1EQvH2Y+U5S2idbLtxs=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css" crossorigin="anonymous">
        
      
    

    

    

  

  
  
  <link rel="stylesheet" href=//fonts.googleapis.com/css?family=Playfair+Display:400,700|EB+Garamond>
  

  <link rel="stylesheet" href="/styles.css">
  
  <link rel="stylesheet" href="/css/override.css">
  

  
  
    <script>
      window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
      ga('create', 'UA-127634411-1', 'auto');
      
      ga('require', 'eventTracker');
      ga('require', 'outboundLinkTracker');
      ga('require', 'urlChangeTracker');
      ga('send', 'pageview');
    </script>
    <script async src="//www.google-analytics.com/analytics.js"></script>
    
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/autotrack/2.4.1/autotrack.js" integrity="sha512-HUmooslVKj4m6OBu0OgzjXXr+QuFYy/k7eLI5jdeEy/F4RSgMn6XRWRGkFi5IFaFgy7uFTkegp3Z0XnJf3Jq+g==" crossorigin="anonymous"></script>
    
  
  

  
  <link rel="alternate" href="/index.xml" type="application/rss+xml" title="Consulting Statistician">
  <link rel="feed" href="/index.xml" type="application/rss+xml" title="Consulting Statistician">
  

  <link rel="manifest" href="/site.webmanifest">
  <link rel="icon" type="image/png" href="/img/icon.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/icon-192.png">

  <link rel="canonical" href="/post/tidytuesday2019/week-2-imdb-tv-shows-data/">

  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@Amalan_Con_Stat">
  <meta property="twitter:creator" content="@Amalan_Con_Stat">
  
  <meta property="og:site_name" content="Consulting Statistician">
  <meta property="og:url" content="/post/tidytuesday2019/week-2-imdb-tv-shows-data/">
  <meta property="og:title" content="Week 2: IMDB TV Shows Data | Consulting Statistician">
  <meta property="og:description" content="2019 Week 2 TidyTuesday: Imdb Tv Shows.">
  
  
    
  <meta property="og:image" content="/img/portray.jpg">
  <meta property="og:locale" content="en-gb">
  
  <meta property="article:published_time" content="2019-01-08T00:00:00&#43;00:00">
  
  <meta property="article:modified_time" content="2019-01-08T00:00:00&#43;00:00">
  

  

  

  <title>Week 2: IMDB TV Shows Data | Consulting Statistician</title>

</head>
<body id="top" data-spy="scroll" data-target="#TableOfContents" data-offset="71" >

<nav class="navbar navbar-light fixed-top navbar-expand-lg py-0" id="navbar-main">
  <div class="container">

    
      <a class="navbar-brand" href="/"><img src="/img/equations.png" alt="Consulting Statistician"></a>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse"
              data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fas fa-bars"></i></span>
      </button>
      

    
    <div class="collapse navbar-collapse" id="navbar">

      
      
      <ul class="navbar-nav ml-auto">
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/#about">
            
            <span>Home</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/#skills">
            
            <span>Talents</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/#experience">
            
            <span>Experience</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/#publications">
            
            <span>Publications</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/#posts">
            
            <span>Posts</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/#projects">
            
            <span>Interests</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/#twitter">
            
            <span>Tweets</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/#contact">
            
            <span>Contact</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/files/Amalan_Mahendran.pdf">
            
            <span>CV</span>
            
          </a>
        </li>

        
        

      

        

        
      </ul>

    </div>
  </div>
</nav>


<article class="article" itemscope itemtype="http://schema.org/Article">

  













<div class="article-header d-xl-none">
  <img src="/post/tidytuesday2019/week-2-imdb-tv-shows-data/featured_hudc450574f8517129b13d881b6dcb81b1_40327_1600x400_fill_q90_box_smart1_2.png" class="article-banner" itemprop="image" alt="">
  
</div>


<div class="container-fluid split-header d-none d-xl-block">
  <div class="row">
    <div class="col-6">
      <div class="split-header-content">
        <h1 itemprop="name">Week 2: IMDB TV Shows Data</h1>

        

        

<div class="article-metadata">

  
  
  <span itemscope itemprop="author" itemtype="http://schema.org/Person">
    <meta itemprop="name" content="Amalan Mahendran">
  </span>
  

  <span class="article-date">
    
    <meta content="2019-01-08 00:00:00 &#43;0000 UTC" itemprop="datePublished">
    <time datetime="2019-01-08 00:00:00 &#43;0000 UTC" itemprop="dateModified">
      Jan 8, 2019
    </time>
  </span>
  <span itemscope itemprop="publisher" itemtype="http://schema.org/Person">
    <meta itemprop="name" content="Amalan Mahendran">
  </span>

  

  
  

  
  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder"></i>
    
    <a href="/categories/tidytuesday/">TidyTuesday</a>
    
  </span>
  
  

  

</div>


        
<div class="share-box" aria-hidden="true">
  <ul class="share">
    <li>
      <a class="twitter"
         href="https://twitter.com/intent/tweet?text=Week%202%3a%20IMDB%20TV%20Shows%20Data&amp;url=%2fpost%2ftidytuesday2019%2fweek-2-imdb-tv-shows-data%2f"
         target="_blank" rel="noopener">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
    <li>
      <a class="facebook"
         href="https://www.facebook.com/sharer.php?u=%2fpost%2ftidytuesday2019%2fweek-2-imdb-tv-shows-data%2f"
         target="_blank" rel="noopener">
        <i class="fab fa-facebook-f"></i>
      </a>
    </li>
    <li>
      <a class="linkedin"
         href="https://www.linkedin.com/shareArticle?mini=true&amp;url=%2fpost%2ftidytuesday2019%2fweek-2-imdb-tv-shows-data%2f&amp;title=Week%202%3a%20IMDB%20TV%20Shows%20Data"
         target="_blank" rel="noopener">
        <i class="fab fa-linkedin-in"></i>
      </a>
    </li>
    <li>
      <a class="weibo"
         href="http://service.weibo.com/share/share.php?url=%2fpost%2ftidytuesday2019%2fweek-2-imdb-tv-shows-data%2f&amp;title=Week%202%3a%20IMDB%20TV%20Shows%20Data"
         target="_blank" rel="noopener">
        <i class="fab fa-weibo"></i>
      </a>
    </li>
    <li>
      <a class="email"
         href="mailto:?subject=Week%202%3a%20IMDB%20TV%20Shows%20Data&amp;body=%2fpost%2ftidytuesday2019%2fweek-2-imdb-tv-shows-data%2f">
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  </ul>
</div>


      </div>
    </div>
    <div class="col-6">
      <div class="split-header-image">
        <img src="/post/tidytuesday2019/week-2-imdb-tv-shows-data/featured_hudc450574f8517129b13d881b6dcb81b1_40327_680x500_fill_q90_box_smart1_2.png" itemprop="image" alt="">
        
      </div>
    </div>
  </div>
</div>

<div class="article-container d-xl-none">
  <h1 itemprop="name">Week 2: IMDB TV Shows Data</h1>

  

  

<div class="article-metadata">

  
  
  <span itemscope itemprop="author" itemtype="http://schema.org/Person">
    <meta itemprop="name" content="Amalan Mahendran">
  </span>
  

  <span class="article-date">
    
    <meta content="2019-01-08 00:00:00 &#43;0000 UTC" itemprop="datePublished">
    <time datetime="2019-01-08 00:00:00 &#43;0000 UTC" itemprop="dateModified">
      Jan 8, 2019
    </time>
  </span>
  <span itemscope itemprop="publisher" itemtype="http://schema.org/Person">
    <meta itemprop="name" content="Amalan Mahendran">
  </span>

  

  
  

  
  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder"></i>
    
    <a href="/categories/tidytuesday/">TidyTuesday</a>
    
  </span>
  
  

  
  
<div class="share-box" aria-hidden="true">
  <ul class="share">
    <li>
      <a class="twitter"
         href="https://twitter.com/intent/tweet?text=Week%202%3a%20IMDB%20TV%20Shows%20Data&amp;url=%2fpost%2ftidytuesday2019%2fweek-2-imdb-tv-shows-data%2f"
         target="_blank" rel="noopener">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
    <li>
      <a class="facebook"
         href="https://www.facebook.com/sharer.php?u=%2fpost%2ftidytuesday2019%2fweek-2-imdb-tv-shows-data%2f"
         target="_blank" rel="noopener">
        <i class="fab fa-facebook-f"></i>
      </a>
    </li>
    <li>
      <a class="linkedin"
         href="https://www.linkedin.com/shareArticle?mini=true&amp;url=%2fpost%2ftidytuesday2019%2fweek-2-imdb-tv-shows-data%2f&amp;title=Week%202%3a%20IMDB%20TV%20Shows%20Data"
         target="_blank" rel="noopener">
        <i class="fab fa-linkedin-in"></i>
      </a>
    </li>
    <li>
      <a class="weibo"
         href="http://service.weibo.com/share/share.php?url=%2fpost%2ftidytuesday2019%2fweek-2-imdb-tv-shows-data%2f&amp;title=Week%202%3a%20IMDB%20TV%20Shows%20Data"
         target="_blank" rel="noopener">
        <i class="fab fa-weibo"></i>
      </a>
    </li>
    <li>
      <a class="email"
         href="mailto:?subject=Week%202%3a%20IMDB%20TV%20Shows%20Data&amp;body=%2fpost%2ftidytuesday2019%2fweek-2-imdb-tv-shows-data%2f">
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  </ul>
</div>


  

</div>

</div>



  <div class="article-container">

    <div class="article-style" itemprop="articleBody">
      

<div id="TOC">
<ul>
<li><a href="#genre">Genre</a><ul>
<li><a href="#genre-and-season">Genre and Season</a></li>
<li><a href="#genre-and-year">Genre and Year</a></li>
<li><a href="#genre-and-month">Genre and Month</a></li>
</ul></li>
<li><a href="#season">Season</a><ul>
<li><a href="#season-and-year">Season and Year</a></li>
<li><a href="#season-and-month">Season and Month</a></li>
</ul></li>
<li><a href="#top-3-genres">Top 3 Genres</a><ul>
<li><a href="#crime-drama-mystery">Crime Drama Mystery</a></li>
<li><a href="#comedy-drama">Comedy Drama</a></li>
<li><a href="#drama">Drama</a></li>
</ul></li>
<li><a href="#rating-over-the-years">Rating over the years</a></li>
<li><a href="#tv-series-with-more-than-14-seasons">Tv Series with more than 14 Seasons</a></li>
</ul>
</div>

<pre class="r"><code># loading the packages
library(tidyverse)
library(summarytools)
library(magrittr)
library(readr)
library(lubridate)
library(gganimate)
library(stringr)

# load the dataset
Ratings &lt;- read_csv(&quot;IMDb_Economist_tv_ratings.csv&quot;, 
                    col_types = cols(date = col_date(format = &quot;%Y-%m-%d&quot;)))</code></pre>
<p><a href="https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-01-08">Ratings</a> data-set is from the IMDB site. I just found out that IMDb is active from 1990, that is a very long time and new information to me.</p>
<p><blockquote class="twitter-tweet"><p lang="en" dir="ltr">The code in GitHub: <a href="https://t.co/ITQnSRH7Ot">https://t.co/ITQnSRH7Ot</a>  <br>.Week 2 of 2019.  Rating over the year and changes in sharing.  <a href="https://twitter.com/hashtag/TidyTuesday?src=hash&amp;ref_src=twsrc%5Etfw">#TidyTuesday</a> <a href="https://t.co/xP5F7PWDFV">pic.twitter.com/xP5F7PWDFV</a></p>&mdash; Amalan Mahendran (@Amalan_Con_Stat) <a href="https://twitter.com/Amalan_Con_Stat/status/1082693109304168448?ref_src=twsrc%5Etfw">January 8, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
 <a href="&#39;https://github.com/Amalan-ConStat/TidyTuesday/tree/master/2019/week2">GitHub code</a></p>
<p>TV shows from 1990 to 2018 with their ratings, genres, sharing and aired dates is in this data-set. I wanted a cool function to summarize the data-set at once, therefore browse through the internet and found the package <a href="https://github.com/dcomtois/summarytools">summarytools</a>. There are quite a few functions in the mix, yet I choose dfSummary.</p>
<p>Below is the code of using that function on the Ratings data-set.</p>
<pre class="r"><code>#Basic summary of all variables
dfSummary(Ratings,style = &#39;grid&#39;)</code></pre>
<pre><code>## Data Frame Summary   
## Ratings     
## **Dimensions:** 2266 x 7     
## **Duplicates:** 1   
## 
## +----+---------------+--------------------------------+----------------------+----------------------------------------+--------+---------+
## | No | Variable      | Stats / Values                 | Freqs (% of Valid)   | Text Graph                             | Valid  | Missing |
## +====+===============+================================+======================+========================================+========+=========+
## | 1  | titleId       | 1. tt0098844                   | 20 ( 0.9%)           |                                        | 2266   | 0       |
## |    | [character]   | 2. tt0203259                   | 20 ( 0.9%)           |                                        | (100%) | (0%)    |
## |    |               | 3. tt0118401                   | 19 ( 0.8%)           |                                        |        |         |
## |    |               | 4. tt0108757                   | 15 ( 0.7%)           |                                        |        |         |
## |    |               | 5. tt0247082                   | 15 ( 0.7%)           |                                        |        |         |
## |    |               | 6. tt0413573                   | 15 ( 0.7%)           |                                        |        |         |
## |    |               | 7. tt0452046                   | 14 ( 0.6%)           |                                        |        |         |
## |    |               | 8. tt0118375                   | 13 ( 0.6%)           |                                        |        |         |
## |    |               | 9. tt0460681                   | 13 ( 0.6%)           |                                        |        |         |
## |    |               | 10. tt0460627                  | 12 ( 0.5%)           |                                        |        |         |
## |    |               | [ 866 others ]                 | 2110 (93.1%)         | IIIIIIIIIIIIIIIIII                     |        |         |
## +----+---------------+--------------------------------+----------------------+----------------------------------------+--------+---------+
## | 2  | seasonNumber  | mean (sd) : 3.26 (3.44)        | 27 distinct values   | :                                      | 2266   | 0       |
## |    | [numeric]     | min &lt; med &lt; max :              |                      | :                                      | (100%) | (0%)    |
## |    |               | 1 &lt; 2 &lt; 44                     |                      | :                                      |        |         |
## |    |               | IQR (CV) : 3 (1.05)            |                      | :                                      |        |         |
## |    |               |                                |                      | : .                                    |        |         |
## +----+---------------+--------------------------------+----------------------+----------------------------------------+--------+---------+
## | 3  | title         | 1. Law &amp; Order                 | 20 ( 0.9%)           |                                        | 2266   | 0       |
## |    | [character]   | 2. Law &amp; Order: Special Vict   | 20 ( 0.9%)           |                                        | (100%) | (0%)    |
## |    |               | 3. Midsomer Murders            | 19 ( 0.8%)           |                                        |        |         |
## |    |               | 4. CSI: Crime Scene Investig   | 15 ( 0.7%)           |                                        |        |         |
## |    |               | 5. ER                          | 15 ( 0.7%)           |                                        |        |         |
## |    |               | 6. Grey&#39;s Anatomy              | 15 ( 0.7%)           |                                        |        |         |
## |    |               | 7. Criminal Minds              | 14 ( 0.6%)           |                                        |        |         |
## |    |               | 8. King of the Hill            | 13 ( 0.6%)           |                                        |        |         |
## |    |               | 9. Supernatural                | 13 ( 0.6%)           |                                        |        |         |
## |    |               | 10. Bones                      | 12 ( 0.5%)           |                                        |        |         |
## |    |               | [ 858 others ]                 | 2110 (93.1%)         | IIIIIIIIIIIIIIIIII                     |        |         |
## +----+---------------+--------------------------------+----------------------+----------------------------------------+--------+---------+
## | 4  | date          | min : 1990-01-03               | 1808 distinct val.   |                   :                    | 2266   | 0       |
## |    | [Date]        | med : 2012-12-07               |                      |                 . :                    | (100%) | (0%)    |
## |    |               | max : 2018-10-10               |                      |               . : :                    |        |         |
## |    |               | range : 28y 9m 7d              |                      |           . : : : :                    |        |         |
## |    |               |                                |                      | . . . . : : : : : :                    |        |         |
## +----+---------------+--------------------------------+----------------------+----------------------------------------+--------+---------+
## | 5  | av_rating     | mean (sd) : 8.06 (0.67)        | 1997 distinct values |               :                        | 2266   | 0       |
## |    | [numeric]     | min &lt; med &lt; max :              |                      |               : :                      | (100%) | (0%)    |
## |    |               | 2.7 &lt; 8.11 &lt; 9.68              |                      |               : :                      |        |         |
## |    |               | IQR (CV) : 0.76 (0.08)         |                      |             . : :                      |        |         |
## |    |               |                                |                      |             : : : .                    |        |         |
## +----+---------------+--------------------------------+----------------------+----------------------------------------+--------+---------+
## | 6  | share         | mean (sd) : 1.28 (3.38)        | 454 distinct values  | :                                      | 2266   | 0       |
## |    | [numeric]     | min &lt; med &lt; max :              |                      | :                                      | (100%) | (0%)    |
## |    |               | 0 &lt; 0.32 &lt; 55.65               |                      | :                                      |        |         |
## |    |               | IQR (CV) : 0.99 (2.64)         |                      | :                                      |        |         |
## |    |               |                                |                      | :                                      |        |         |
## +----+---------------+--------------------------------+----------------------+----------------------------------------+--------+---------+
## | 7  | genres        | 1. Crime,Drama,Mystery         | 369 (16.3%)          | III                                    | 2266   | 0       |
## |    | [character]   | 2. Comedy,Drama                | 174 ( 7.7%)          | I                                      | (100%) | (0%)    |
## |    |               | 3. Drama                       | 168 ( 7.4%)          | I                                      |        |         |
## |    |               | 4. Action,Crime,Drama          | 146 ( 6.4%)          | I                                      |        |         |
## |    |               | 5. Action,Adventure,Drama      | 112 ( 4.9%)          |                                        |        |         |
## |    |               | 6. Crime,Drama                 | 107 ( 4.7%)          |                                        |        |         |
## |    |               | 7. Drama,Romance               | 86 ( 3.8%)           |                                        |        |         |
## |    |               | 8. Comedy,Crime,Drama          | 80 ( 3.5%)           |                                        |        |         |
## |    |               | 9. Comedy,Drama,Romance        | 76 ( 3.4%)           |                                        |        |         |
## |    |               | 10. Crime,Drama,Thriller       | 63 ( 2.8%)           |                                        |        |         |
## |    |               | [ 87 others ]                  | 885 (39.1%)          | IIIIIII                                |        |         |
## +----+---------------+--------------------------------+----------------------+----------------------------------------+--------+---------+</code></pre>
<p>Basic summary of seasons indicate 27 distinct values and obviously 1 is the minimum value, but the maximum value is 44. Another odd thing is median for being 2, further the average is 3.26. Which means most of the TV shows have only up-to few seasons. I would guess not more than 5.</p>
<p>Summary of date indicates the earliest TV show from 1990 and latest from 2018. So the year difference is 28 years, but there are only 1808 distinct values. Even though the data-set contains 2266 observations. Some TV shows might have to start on the same day, that is the only plausible conclusion.</p>
<p>“av_rating” (I presume Audio/Video Rating) is in the scale from 1 to 10, where people had influence. The least rating value is 2.7 and the most rating value is 9.68, but the median is 8.11. Also the mean is 8.06. We can say most of these TV shows are excellent to watch. There is another numeric variable called share and the value ranges from 0 to 55.65 where the average is 1.28.</p>
<div id="genre" class="section level1">
<h1>Genre</h1>
<p>Genres in this data-set has close to 100 distinct factors. The category “Crime,Drama,Mystery” holds the highest percentage of 16.3, while second place is to “Comedy,Drama” with 7.7% and third place is to “Drama” type with 7.4%. All the other types of genre is represented by less than 7%.</p>
<div id="genre-and-season" class="section level2">
<h2>Genre and Season</h2>
<p>Genre and Season are two categorical variables which should be compared to find out if over time do people like the same genre type. If we look at the bar plot it is clear “Crime,Drama,Mystery” type has seasons from 1 to 20. Mostly in all genres there is clear sign of TV shows with seasons up-to three or four. Some of them make it to season ten or eleven, for example genres like “Drama”, “Drama,Thriller”, “Animation,Comedy,Drama” and “Adventure,Drama,Family”.</p>
<p>Oddly in “Drama,Romance” and “Crime,Drama” there are TV shows which has seasons above 35 but very few. It becomes more weird where for the same genre types the seasons in-between 25 and 34 are missing. Clearly in the legend also until season 20 there is continuity, but this does not carry on for higher seasons.</p>
<pre class="r"><code>ggplot(Ratings,aes(x=fct_infreq(factor(genres)),fill=factor(seasonNumber)))+
  geom_bar()+ coord_flip()+labs(fill=&quot;Season&quot;)+
  xlab(&quot;Genre&quot;)+ylab(&quot;Frequency&quot;)+
  ggtitle(&quot;Genre and Seasons&quot;)+
  scale_y_continuous(breaks=seq(0,375,25),labels=seq(0,375,25))</code></pre>
<p><img src="/post/TidyTuesday2019/Week2/index_files/figure-html/Genre%20vs%20Season-1.png" width="1152" /></p>
</div>
<div id="genre-and-year" class="section level2">
<h2>Genre and Year</h2>
<p>Bar plot indicates that after 2014 around 90% of these genre type TV shows have been done. In the top ten category according to the counts of TV shows clearly all of these genres have been active since 1990 to now. Some of them were started in mid 1990s which include the genre types “Action,Crime,Drama”, “Crime,Drama” and “Comedy,Crime,Drama”.</p>
<p>Types such as “Drama,Romance,Sport” and “Adventure,Drama,Romance” were in active in the mid 2000s but no longer. Genres such as “Drama,History”, “Drama,Horror,Thriller” and “Action,Drama” are a few of them which were popular after 2012.</p>
<pre class="r"><code>ggplot(Ratings,aes(x=fct_infreq(factor(genres)),fill=factor(year(date))))+
  geom_bar()+ coord_flip()+labs(fill=&quot;Year&quot;)+
  xlab(&quot;Genre&quot;)+ylab(&quot;Frequency&quot;)+
  ggtitle(&quot;Genre Over the Year&quot;)+
  scale_y_continuous(breaks=seq(0,375,25),labels=seq(0,375,25))</code></pre>
<p><img src="/post/TidyTuesday2019/Week2/index_files/figure-html/Genre%20vs%20Year-1.png" width="1152" /></p>
</div>
<div id="genre-and-month" class="section level2">
<h2>Genre and Month</h2>
<p>Month of airing might have an influence on the TV shows. Bar plot indicates that most of the TV shows are aired in the first quarter or last quarter of the year. Which means shows aired in the fall (September or October) or aired after winter break (January).</p>
<pre class="r"><code>ggplot(Ratings,aes(x=fct_infreq(factor(genres)),fill=factor(month(date))))+
  geom_bar()+ coord_flip()+ labs(fill=&quot;Month&quot;)+
  xlab(&quot;Genre&quot;)+ylab(&quot;Frequency&quot;)+
  ggtitle(&quot;Genre Over the Months&quot;)+
  scale_y_continuous(breaks=seq(0,375,25),labels=seq(0,375,25))</code></pre>
<p><img src="/post/TidyTuesday2019/Week2/index_files/figure-html/Genre%20vs%20Month-1.png" width="1152" /></p>
</div>
</div>
<div id="season" class="section level1">
<h1>Season</h1>
<p>TV shows may run for few seasons or more most of the time. Some are limited seasons close to four or above, but definitely less than 10. It is very rare to see TV shows going beyond the 15 seasons mark.</p>
<div id="season-and-year" class="section level2">
<h2>Season and Year</h2>
<p>Clearly there is an increase in TV shows aired over the years. All time low occurs in 1992 but all time high occurs in 2017. From 1990 to 2010 the TV shows aired have increased from 25 to 100. By the end of year 2017 the number of shows aired has reached more than 250, but its drops to slightly above 175 the next year. The all time low of less than 12 seasons occurs in 1990.</p>
<p>In the years 1990,1996,2005,2007,2010,2011 and 2015 there are TV shows which has season above 30, but it should be reminded that according to the legend after season 20 there is no continuity.</p>
<p>If we focus closely until 2005 most of the TV shows have seasons up-to 10 , but after 2005 there are TV shows which aired season until 20. This shows the popularity of certain shows over three decades.</p>
<pre class="r"><code>ggplot(Ratings,aes(x=factor(year(date)),fill=factor(seasonNumber)))+
  geom_bar()+ coord_flip()+labs(fill=&quot;Season&quot;)+
  xlab(&quot;Year&quot;)+ylab(&quot;Frequency&quot;)+
  ggtitle(&quot;Seasons over the Years&quot;)+
  scale_y_continuous(breaks=seq(0,230,10),labels=seq(0,230,10))</code></pre>
<p><img src="/post/TidyTuesday2019/Week2/index_files/figure-html/Season%20vs%20Year-1.png" width="1152" /></p>
</div>
<div id="season-and-month" class="section level2">
<h2>Season and Month</h2>
<p>Highest amount of more than 500 shows were aired in January and lowest amount of slightly less than 100 was aired in June. Second place goes to February with shows close to 200 being aired this is not even the half of what aired in the previous month. In the months of January, February and September most of the seasons were aired, while in the other months the seasons aired are from the range of 1 to 10. Where very few of them ever reached the double digits or above season 8.</p>
<pre class="r"><code>ggplot(Ratings,aes(x=factor(month(date)),fill=factor(seasonNumber)))+
  geom_bar()+coord_flip()+labs(fill=&quot;Season&quot;)+
  xlab(&quot;Month&quot;)+ylab(&quot;Frequency&quot;)+
  ggtitle(&quot;Seasons over the months&quot;)+
  scale_y_continuous(breaks=seq(0,550,25),labels=seq(0,550,25))</code></pre>
<p><img src="/post/TidyTuesday2019/Week2/index_files/figure-html/Season%20vs%20Month-1.png" width="1152" /></p>
</div>
</div>
<div id="top-3-genres" class="section level1">
<h1>Top 3 Genres</h1>
<p>Let focus on the most mentioned genre types which are “Crime,Drama,Mystery”, “Comedy,Drama” and “Drama”. The below section is to graphically represent the TV shows of a certain genre with its seasons and when they were aired.</p>
<p>Therefore I will not be factual, mostly biased towards the shows I watched and special characteristics.</p>
<div id="crime-drama-mystery" class="section level2">
<h2>Crime Drama Mystery</h2>
<p>Law and Order of 20 seasons has been over for more than 5 years and it began airing in 1990. Law and Order Special Victims Unit started airing in 1999 even now its still being aired. There are also odd shows like which has not aired continuously and skipped an year or two. Among them Columbo, Agatha Christie’s Marple and II commissario Montalbano are specially noted.</p>
<p>There are lot of shows which only aired one or two seasons only and then stopped. They also can be noted from the bar plot. In the legend there are colors to indicate all the years from 1990 to 2018.</p>
<pre class="r"><code>subset(Ratings,genres==&quot;Crime,Drama,Mystery&quot;) %&gt;%
  ggplot(aes(x=fct_infreq(title),fill=factor(year(date)),color=factor(year(date))))+
    geom_bar()+ coord_flip()+labs(color=&quot;Year&quot;,fill=&quot;Year&quot;)+
    xlab(&quot;TV shows&quot;)+ylab(&quot;Frequency&quot;)+
    ggtitle(&quot;&#39;Crime,Drama,Mystery&#39; Genre type over the Years&quot;)+
    scale_y_continuous(breaks=0:20,labels=0:20)</code></pre>
<p><img src="/post/TidyTuesday2019/Week2/index_files/figure-html/Crime%20Drama%20Mystery-1.png" width="1152" /></p>
</div>
<div id="comedy-drama" class="section level2">
<h2>Comedy Drama</h2>
<p>Similarly as above we can interpret the bar plot as well. But here the highest amount of seasons any TV show has reached is 9. Only the TV shows “Scrubs” and “Shameless” have reached that milestone and both of them begin in different decades. “Scrubs” began in early 2000s, but “Shameless” was aired after 2010.</p>
<p>In the years 1998 and 1999 there were no TV shows aired under the genre “Comedy,Drama”.</p>
<pre class="r"><code>subset(Ratings,genres==&quot;Comedy,Drama&quot;) %&gt;%
    ggplot(aes(x=fct_infreq(title),fill=factor(year(date)),color=factor(year(date))))+
    geom_bar()+ coord_flip()+labs(color=&quot;Year&quot;,fill=&quot;Year&quot;)+
    xlab(&quot;TV shows&quot;)+ylab(&quot;Frequency&quot;)+
    ggtitle(&quot;&#39;Comedy,Drama&#39; Genre type over the Years&quot;)+
    scale_y_continuous(breaks=0:9,labels=0:9)</code></pre>
<p><img src="/post/TidyTuesday2019/Week2/index_files/figure-html/Comedy%20and%20Drama-1.png" width="1152" /></p>
</div>
<div id="drama" class="section level2">
<h2>Drama</h2>
<p>Most of the TV shows in this genre type are limited to one season an a few more with 2 or 3 seasons. Even though most of them were aired after 2015. TV shows “Mad Men”, “Skins” and “The West Wing” has aired for 7 seasons.</p>
<p>Some of these shows were limited series like “The News Room”. The only very early TV show is “Rebel Highway” which was aired in 1994 and in year 2004 “Summerland” was aired, where both of them were limited to one season.</p>
<p>According to the legend the years 1992,1993,1995 to 1998 were years free of “Drama” genre TV shows.</p>
<pre class="r"><code>subset(Ratings,genres==&quot;Drama&quot;) %&gt;%
 ggplot(aes(x=fct_infreq(title),fill=factor(year(date)),color=factor(year(date))))+
    geom_bar()+ coord_flip()+labs(color=&quot;Year&quot;,fill=&quot;Year&quot;)+
    xlab(&quot;TV shows&quot;)+ylab(&quot;Frequency&quot;)+
    ggtitle(&quot;&#39;Drama&#39; Genre type over the Years&quot;)+
    scale_y_continuous(breaks=0:7,labels=0:7)</code></pre>
<p><img src="/post/TidyTuesday2019/Week2/index_files/figure-html/Drama-1.png" width="1152" /></p>
</div>
</div>
<div id="rating-over-the-years" class="section level1">
<h1>Rating over the years</h1>
<p>Lets discuss regarding TV shows and their rating over the years with related to sharing. Clearly we can see the number of shows increasing from 1990 to 2018. Oddly there was more sharing related to TV shows before 2000, but this is not the case after the birth of Millenium. To be honest sharing becomes more extinct even with the power of Internet and smart phones.</p>
<p>In perspective of rating the range is very much centered and small(between 7.5 - 9), but over the years this changes and expands to a wider range.(6.5 - 9.5). Only a handful of TV shows are rated below 5 in the scale over the year span of 28.</p>
<pre class="r"><code>p&lt;-ggplot(Ratings,aes(x=factor(year(date)),y=av_rating,color=genres,size=share))+
      geom_point(show.legend = FALSE)+ 
      labs(title = &quot;Ratings and Sharing : {frame_time}&quot;
           ,x=&quot;Year&quot;,y=&quot;Rating&quot;)+
      scale_y_continuous(breaks=2:10,labels=2:10)+
      transition_time(date)+ease_aes(&#39;linear&#39;)+
      theme(axis.text.x = element_text(angle = 90))+
      shadow_mark()

animate(p,fps= 5,duration =60)</code></pre>
<p><img src="/post/TidyTuesday2019/Week2/index_files/figure-html/Rating%20vs%20Years-1.gif" /><!-- --></p>
</div>
<div id="tv-series-with-more-than-14-seasons" class="section level1">
<h1>Tv Series with more than 14 Seasons</h1>
<p>This is simply me trying to focus on the TV shows which has seasons more than 14 and their rating, sharing changes over the years.</p>
<pre class="r"><code>p&lt;-subset(Ratings,title==&quot;CSI: Crime Scene Investigation&quot;|
          title==&quot;ER&quot;| title==&quot;Grey&#39;s Anatomy&quot;| title==&quot;Midsomer Murders&quot;| 
          title==&quot;Law &amp; Order&quot;|
          title==&quot;Law &amp; Order: Special Victims Unit&quot;) %&gt;%
ggplot(aes(x=seasonNumber,y=av_rating,color=title,size=share))+ 
      geom_point()+
      labs(title = &#39;Season and Rating Year: {frame_time}&#39;,
           x=&quot;Season&quot;,y=&quot;Rating&quot;)+
      scale_x_continuous(breaks=1:20,labels=1:20)+
      #scale_y_continuous(breaks=)
      transition_time(date)+ease_aes(&#39;linear&#39;)+
      shadow_mark()+theme(legend.position = &quot;bottom&quot;)

animate(p,fps=5,duration = 60)</code></pre>
<p><img src="/post/TidyTuesday2019/Week2/index_files/figure-html/More%20than%2014%20Seasons-1.gif" /><!-- --></p>
<p><em>THANK YOU</em></p>
</div>

    </div>

    


<div class="article-tags">
  
  <a class="badge badge-light" href="/tags/tidytuesday/">TidyTuesday</a>
  
  <a class="badge badge-light" href="/tags/r/">R</a>
  
  <a class="badge badge-light" href="">R package</a>
  
  <a class="badge badge-light" href="/tags/tidyverse/">tidyverse</a>
  
  <a class="badge badge-light" href="/tags/gganimate/">gganimate</a>
  
</div>




    
    
    <div class="article-widget">
      <div class="hr-light"></div>
      <h3>Related</h3>
      <ul>
        
        <li><a href="/post/tidytuesday2019/week-1-tidytuesday-tweets/">2019 Week 1 : #TidyTuesday Tweets </a></li>
        
        <li><a href="/post/week-34-thanksgiving/">Week 34 : Thanksgiving </a></li>
        
        <li><a href="/post/week-33-malaria-deaths/">Week 33 : Malaria Deaths</a></li>
        
        <li><a href="/post/week-31-r-and-package-downloads/">Week 31 : R and Package Downloads</a></li>
        
        <li><a href="/post/week-30-movie-profit/">Week 30: Movie Profit</a></li>
        
      </ul>
    </div>
    

    

    


  </div>
</article>

<div class="container">
  <footer class="site-footer">
  
  <p class="powered-by">
    <a href="/privacy/">Privacy Policy of MIT</a>
  </p>
  

  <p class="powered-by">
    &copy; 2018 &middot; 

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" id="back_to_top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

</div>


<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

    

    
    
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        CommonHTML: { linebreaks: { automatic: true } },
        tex2jax: { inlineMath: [ ['$', '$'], ['\\(','\\)'] ], displayMath: [ ['$$','$$'], ['\\[', '\\]'] ], processEscapes: false },
        TeX: { noUndefined: { attributes: { mathcolor: 'red', mathbackground: '#FFEEEE', mathsize: '90%' } } },
        messageStyle: 'none'
      });
    </script>
    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha512-+NqPlbbtM1QqiK8ZAo4Yrj2c4lNQoGv8P79DPtKzj++l5jnN39rHA/xsqn8zE9l0uSoxaCdrOgFs6yjyfbBxSg==" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.3/imagesloaded.pkgd.min.js" integrity="sha512-umsR78NN0D23AzgoZ11K7raBD+R6hqKojyBZs1w8WvYlsI+QuKRGBx3LFCwhatzBunCjDuJpDHwxD13sLMbpRA==" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha256-VsEqElsCHSGmnmHXGQzvoWjWwoznFSZc6hs7ARLRacQ=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.4/isotope.pkgd.min.js" integrity="sha512-VDBOIlDbuC4VWxGJNmuFRQ0Li0SKkDpmGyuhAG5LTDLd/dJ/S0WMVxriR2Y+CyPL5gzjpN4f/6iqWVBJlht0tQ==" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" integrity="sha256-X5PoE3KU5l+JcX+w09p/wHl9AzK333C4hJ2I9S5mD4M=" crossorigin="anonymous"></script>

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js" integrity="sha256-/BfiIkHlHoVihZdc6TFuj7MmJ0TWcWsMXkeDFwhi0zw=" crossorigin="anonymous"></script>
        
        <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
        
        <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/python.min.js"></script>
        
      

      
      
      <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_CHTML-full" integrity="sha256-GhM+5JHb6QUzOQPXSJLEWP7R73CbkisjzK5Eyij4U9w=" crossorigin="anonymous" async></script>
      
    

    <script src="/js/hugo-academic.js"></script>
    

    
    

    
    
    

    
    
    <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script>
      const search_index_filename = "/index.json";
      const i18n = {
        'placeholder': "Search...",
        'results': "Search Results",
        'no_results': "No results found"
      };
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    <script src="/js/search.js"></script>
    

    
    

  </body>
</html>

