---
title: Build Your Own Website or Blog Using R, RStudio and R Packages.
author: M.Amalan
date: '2019-01-28'
output: 
  blogdown::html_page:
    toc: true
slug: build-your-own-website-or-blog-using-r-rstudio-and-r-packages
categories:
  - R
  - Website
  - Blog
tags:
  - R
  - R package
  - Website
image:
  caption: ''
  focal_point: ''
summary: "Useful information on how to develop your own website or blog using R."  
---

# Introduction

R enthusiasts are focused on developing packages and websites to promote their profile and share 
their knowledge to the world. Recently released packages such as hugo, blogdown, Rmarkdown, bookdown 
has played a significant amount of role in this popularity for R statistical software among 
general users and academics in every field of statistics.

Due to this reason, I also wanted to develop my own R package to solve problem in hand and share
it with the #rstats community. Even though Social Media is a strong way of sharing this amount of
information, it is not sturdy over time. To resolve this only I chose to develop my own website
using R and supportive tools from R. You are reading this post on my website which I developed in a 
very short period of time and have being maintaining regularly by posting articles. 

# Materials

I could have written an extensive and long article describing how I developed this website with 
screenshots and explanatory steps. As it should be a valuable experience I am only going
to give you the materials which were used with important points with facts. Further, I shall
give you certain specifics of my own website.
 
## "Making Websites with Rmarkdown and Blogdown by Yihui Xie."

[Link](https://slides.yihui.name/2017-rstudio-webinar-blogdown-Yihui-Xie.html#1)

* Presentation of 20 slides.
* Most of the basic information for packages which are necessary for website development.
* Brief introduction about the website structure and process.

## "Up and Running with Blogdown by Alison Presmanes Hill."

[Link](https://alison.rbind.io/post/up-and-running-with-blogdown/)

* Brief information for blogdown and other development materials.
* Described information Deployment and maintaining the website with 
  other tools related to R and Rstudio.

## "Rmarkdown Websites."

[Link](https://rmarkdown.rstudio.com/lesson-13.html)

* Briefest description about using Rmarkdown/Rmd files for website development.
* There are few other links which could be considered useful.

## "How to make an RMarkdown Website by Nick Strayer & Lucy D'Agostino McGowan."

[Link](http://nickstrayer.me/RMarkdown_Sites_tutorial/)

* One example sample website developed and explained briefly by the authors.
* Several links to spark curiosity about website development using Rmarkdown.

## "Creating websites in R by Emily C Zabor."

[Link](http://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html)

* Explanation on different type of websites which can be produced by R.
* Deployment and additional requirements for website development.

## "Getting Started with Blogdown by David Selby."

[Link](https://selbydavid.com/wrugdown/2017/05/10/getting-started-with-blogdown/)

* Limited amount of information regarding website development.
* This was written for a talk for the "Warwick R User Group Talk" in 2017.

## "Getting Started with Blogdown by Danielle Navarro."

[Link](http://djnavarro.net/post/2018-04-27-starting-blogdown/)

* Extensive amount of information about website development using blogdown.
* More than enough information about the insides of the website.
* Detailed steps of writing posts and changing elements of the website.

## "Blogdown by Peter's Blog."

[Link](https://notes.peter-baumgartner.net/tags/blogdown/)

* 4 Tutorials explaining from scratch about how to develop your website using blogdown.
* Tutorial 1 explains about website themes and setting up R and Rstudio.
* Tutorial 2 is about hosting the website locally or sharing the work with others.
* Tutorial 3 will be information about getting the site live.
* Tutorial 4 describes how to bring the website online through Netlify or GitHub.

## "Academic by George Cushen"

[Link](https://sourcethemes.com/academic/)

* All the information about the academic theme this is very popular among people in rstats community.
* Descriptive amount of information about changing elements in the academic theme to make it more
  homely fo the user. 

## "Happy Git and GitHub for the User."

[Link](https://happygitwithr.com/)

* Git and GitHub with R with all the information that anyone needs to know.

## "RMarkdown : The Definitive Guide by Yihui Xie, J. J. Allaire, Garrett Grolemund."

[Link](https://bookdown.org/yihui/rmarkdown/)

* Book with all the information related to Rmarkdown files.
* No need to look anywhere for clarification regarding Rmarkdown.

## "blogdown: Creating Websites with R Markdown by Yihui Xie, Amber Thomas, Alison Presmanes Hill."

[Link](https://bookdown.org/yihui/blogdown/)

* Similar to the previous two books this is also the most useful for blogdown.
* No need to look anywhere else for further understanding regarding blogdown.

# My Personal Website / Blog

Information related to my website / blog will be discussed here.  Mostly encouraging
other people to make necessary changes in the original template to satisfy their curiosity and interest. 

* I also used the academic theme but made alot of changes.
* These changes include with a new css, color changing, font changing and others.
* In the Home page I explored adding icons, heading names and changing the header successfully. 
* While writing blog posts I was able to learn inventive ways to make them interesting. 

For now that is all I have done in related to developing my own website. It should be your own choice
what you are going to develop, a website / blog. Mine is a website where articles are regularly posted.
Further, it should be noted that the above materials were active when I was writing this post, therefore
if it is not active do use google and try to find it. 

*THANK YOU*