---
title: 'Week 33: Roman Emperors'
author: M.Amalan
date: '2019-08-13'
categories:
  - TidyTuesday
tags:
  - ggpol
  - ggplot
  - TidyTuesday
slug: Week33
output:
  blogdown::html_page:
    toc: yes
image:
  caption: ''
  focal_point: ''
summary: '2019 Week 33 TidyTuesday: Roman Emperors, Right!.'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE,message = FALSE,fig.width = 12,fig.height = 9)
```

This is a very small data frame, which is with 68 observations and 16 variables. Several plots were
generated but main focus was on using the 'ggpol' package. 

```{r lading data and packages}
# load the data
emperors <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-08-13/emperors.csv")

# load packages
library(ggplot2)
library(dplyr)
library(ggpol)

# load theme package
library(ggthemr)
ggthemr("flat")
```

[GitHub Code]()

```{r tweet,echo=FALSE}
#blogdown::shortcode("tweet","")
```

# Birth Province

Initial plots were generated for Birth Province with mostly other categorical variables.

```{r Birth Pro vs Count}
emperors %>%
  group_by(birth_prv) %>%
  count(sort = TRUE) %>%
  ggplot(.,aes(birth_prv,n,label=n))+geom_col()+
  xlab("Birth Province")+ylab("Frequency")+geom_text(vjust=1)+
  ggtitle("Which Birth Province has produced more Emperors?")+
  theme(axis.text.x = element_text(angle=30,hjust=1))
```

```{r Birth Pro vs rise}
ggplot(emperors ,aes(stringr::str_wrap(birth_prv,12),stringr::str_wrap(rise,15),color=era))+
  geom_jitter(shape=15)+xlab("Birth Province")+ylab("Risen to Power")+
  ggtitle("Does Birth Province has any affect in coming to Power?")+
  theme(axis.text.x = element_text(angle=30,hjust=1))
```

```{r Birth Pro vs Time}
emperors %>%
  mutate(reign_time=reign_end-reign_start) %>%
ggplot(.,aes(stringr::str_wrap(birth_prv,12),abs(reign_time),color=era))+
  geom_jitter(shape=15)+
  xlab("Birth Province")+ylab("Days in Power")+
  ggtitle("Days in Power vs Birth Province")+
  theme(axis.text.x = element_text(angle=30,hjust=1))
```

# Reign Time

```{r Reign Time vs Rise}
emperors %>%
  mutate(reign_time=reign_end-reign_start) %>%
ggplot(.,aes(stringr::str_wrap(rise,12),abs(reign_time),color=era))+
  geom_jitter(shape=15)+
  xlab("Rise")+ylab("Days in Power")
```

```{r Reign Time vs Cause}
emperors %>%
  mutate(reign_time=reign_end-reign_start) %>%
ggplot(.,aes(stringr::str_wrap(cause,12),abs(reign_time),color=era))+
  geom_jitter(shape=15)+
  xlab("Cause")+ylab("Days in Power")
```

```{r Reign Time vs Dynasty}
emperors %>%
  mutate(reign_time=reign_end-reign_start) %>%
ggplot(.,aes(stringr::str_wrap(dynasty,12),abs(reign_time),color=era))+
  geom_jitter(shape=15)+
  xlab("Dynasty")+ylab("Days in Power")
```

```{r Reign Time vs Era}
emperors %>%
  mutate(reign_time=reign_end-reign_start) %>%
ggplot(.,aes(stringr::str_wrap(era,12),abs(reign_time),color=dynasty))+
  geom_jitter(shape=15)+
  xlab("Era")+ylab("Days in Power")
```

# Cause and Killer

```{r cause and killer}
ggplot(emperors,aes(cause,killer,color=era))+geom_jitter(shape=15)+
    xlab("Cause")+ylab("Killer")
```


# Using ggpol package

## Era

```{r Era}
emperors$era<-factor(emperors$era)

emperors %>%
  count(era) %>%
ggplot(.) + 
  geom_parliament(aes(seats = n, fill = era)) + 
  scale_fill_manual(values=c("red","yellow"),labels = unique(emperors$era))+
  coord_fixed() + theme_void()
```

## Risen to Power

```{r Rise}
emperors$rise<-factor(emperors$rise)

emperors %>%
  count(rise) %>%
ggplot(.) + 
  geom_parliament(aes(seats = n, fill = rise)) + 
  scale_fill_manual(values=blues9,labels = unique(emperors$rise))+
  coord_fixed() + theme_void()
```

## Cause of Death

```{r Cause}
emperors$cause<-factor(emperors$cause)

emperors %>%
  count(cause) %>%
ggplot(.) + 
  geom_parliament(aes(seats = n, fill = cause)) + 
  scale_fill_manual(values=blues9,labels = unique(emperors$cause))+
  coord_fixed() + theme_void()
```

## Killer

```{r Killer}
emperors$killer<-factor(emperors$killer)

emperors %>%
  count(killer) %>%
ggplot(.) + 
  geom_parliament(aes(seats = n, fill = killer)) + 
  scale_fill_manual(values=c(blues9,"red","yellow","green","grey","black"),
                    labels = unique(emperors$killer))+
  coord_fixed() + theme_void()
```

## Dynasty

```{r Dynasty}
emperors$dynasty<-factor(emperors$dynasty)

emperors %>%
  count(dynasty) %>%
ggplot(.) + 
  geom_parliament(aes(seats = n, fill = dynasty)) + 
  scale_fill_manual(values=blues9,labels = unique(emperors$dynasty))+
  coord_fixed() + theme_void()
```


*THANK YOU*