<!DOCTYPE html>
<html lang="en-gb">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 2.4.0">
  <meta name="generator" content="Hugo 0.49.2" />
  <meta name="author" content="Amalan Mahendran">

  
  
  
  
    
  
  <meta name="description" content="Movie Profit GenerallyIntroductionThis is my second post on Tidy Tuesday and the dataset in question is Movie profit dataset.
# looking at dimensionsdim(Movie)## [1] 3401 8# check for missing values in numerical valuesattach(Movie)summary(release_date)## Length Class Mode ## 3401 character charactersummary(production_budget)## Min. 1st Qu. Median Mean 3rd Qu. Max. ## 250000 9000000 20000000 33284743 45000000 175000000summary(domestic_gross)## Min. 1st Qu.">

  
  <link rel="alternate" hreflang="en-gb" href="/post/week_30/tidy-tuesday-week-30/">

  


  

  

  

  
  
  
  <meta name="theme-color" content="#2962ff">
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" integrity="sha256-ygkqlh3CYSUri3LhQxzdcm0n1EQvH2Y+U5S2idbLtxs=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css" crossorigin="anonymous">
        
      
    

    

    

  

  
  
  <link rel="stylesheet" href=//fonts.googleapis.com/css?family=Lato:400,700|Merriweather|Roboto+Mono>
  

  <link rel="stylesheet" href="/styles.css">
  

  
  
    <script>
      window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
      ga('create', 'UA-127634411-1', 'auto');
      
      ga('require', 'eventTracker');
      ga('require', 'outboundLinkTracker');
      ga('require', 'urlChangeTracker');
      ga('send', 'pageview');
    </script>
    <script async src="//www.google-analytics.com/analytics.js"></script>
    
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/autotrack/2.4.1/autotrack.js" integrity="sha512-HUmooslVKj4m6OBu0OgzjXXr+QuFYy/k7eLI5jdeEy/F4RSgMn6XRWRGkFi5IFaFgy7uFTkegp3Z0XnJf3Jq+g==" crossorigin="anonymous"></script>
    
  
  

  
  <link rel="alternate" href="/index.xml" type="application/rss+xml" title="Consulting Statistician">
  <link rel="feed" href="/index.xml" type="application/rss+xml" title="Consulting Statistician">
  

  <link rel="manifest" href="/site.webmanifest">
  <link rel="icon" type="image/png" href="/img/icon.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/icon-192.png">

  <link rel="canonical" href="/post/week_30/tidy-tuesday-week-30/">

  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@Amalan_Con_Stat">
  <meta property="twitter:creator" content="@Amalan_Con_Stat">
  
  <meta property="og:site_name" content="Consulting Statistician">
  <meta property="og:url" content="/post/week_30/tidy-tuesday-week-30/">
  <meta property="og:title" content="Tidy Tuesday : Week 30 | Consulting Statistician">
  <meta property="og:description" content="Movie Profit GenerallyIntroductionThis is my second post on Tidy Tuesday and the dataset in question is Movie profit dataset.
# looking at dimensionsdim(Movie)## [1] 3401 8# check for missing values in numerical valuesattach(Movie)summary(release_date)## Length Class Mode ## 3401 character charactersummary(production_budget)## Min. 1st Qu. Median Mean 3rd Qu. Max. ## 250000 9000000 20000000 33284743 45000000 175000000summary(domestic_gross)## Min. 1st Qu.">
  
  
    
  <meta property="og:image" content="/img/portray.jpg">
  <meta property="og:locale" content="en-gb">
  
  <meta property="article:published_time" content="2018-11-14T00:00:00&#43;00:00">
  
  <meta property="article:modified_time" content="2018-11-14T00:00:00&#43;00:00">
  

  

  

  <title>Tidy Tuesday : Week 30 | Consulting Statistician</title>

</head>
<body id="top" data-spy="scroll" data-target="#TableOfContents" data-offset="71" >

<nav class="navbar navbar-light fixed-top navbar-expand-lg py-0" id="navbar-main">
  <div class="container">

    
      <a class="navbar-brand" href="/"><img src="/img/equations.png" alt="Consulting Statistician"></a>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse"
              data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fas fa-bars"></i></span>
      </button>
      

    
    <div class="collapse navbar-collapse" id="navbar">

      
      
      <ul class="navbar-nav ml-auto">
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/#about">
            
            <span>Home</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/#skills">
            
            <span>Talents</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/#experience">
            
            <span>Experience</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/#publications">
            
            <span>Publications</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/#posts">
            
            <span>Posts</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/#projects">
            
            <span>Interests</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/#contact">
            
            <span>Contact</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/files/Amalan-Mahendran.pdf">
            
            <span>CV</span>
            
          </a>
        </li>

        
        

      

        

        
      </ul>

    </div>
  </div>
</nav>


<article class="article" itemscope itemtype="http://schema.org/Article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1 itemprop="name">Tidy Tuesday : Week 30</h1>

  

  
    

<div class="article-metadata">

  
  
  <span itemscope itemprop="author" itemtype="http://schema.org/Person">
    <meta itemprop="name" content="Amalan Mahendran">
  </span>
  

  <span class="article-date">
    
    <meta content="2018-11-14 00:00:00 &#43;0000 UTC" itemprop="datePublished">
    <time datetime="2018-11-14 00:00:00 &#43;0000 UTC" itemprop="dateModified">
      Nov 14, 2018
    </time>
  </span>
  <span itemscope itemprop="publisher" itemtype="http://schema.org/Person">
    <meta itemprop="name" content="Amalan Mahendran">
  </span>

  

  
  

  
  
  
  

  
  
<div class="share-box" aria-hidden="true">
  <ul class="share">
    <li>
      <a class="twitter"
         href="https://twitter.com/intent/tweet?text=Tidy%20Tuesday%20%3a%20Week%2030&amp;url=%2fpost%2fweek_30%2ftidy-tuesday-week-30%2f"
         target="_blank" rel="noopener">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
    <li>
      <a class="facebook"
         href="https://www.facebook.com/sharer.php?u=%2fpost%2fweek_30%2ftidy-tuesday-week-30%2f"
         target="_blank" rel="noopener">
        <i class="fab fa-facebook-f"></i>
      </a>
    </li>
    <li>
      <a class="linkedin"
         href="https://www.linkedin.com/shareArticle?mini=true&amp;url=%2fpost%2fweek_30%2ftidy-tuesday-week-30%2f&amp;title=Tidy%20Tuesday%20%3a%20Week%2030"
         target="_blank" rel="noopener">
        <i class="fab fa-linkedin-in"></i>
      </a>
    </li>
    <li>
      <a class="weibo"
         href="http://service.weibo.com/share/share.php?url=%2fpost%2fweek_30%2ftidy-tuesday-week-30%2f&amp;title=Tidy%20Tuesday%20%3a%20Week%2030"
         target="_blank" rel="noopener">
        <i class="fab fa-weibo"></i>
      </a>
    </li>
    <li>
      <a class="email"
         href="mailto:?subject=Tidy%20Tuesday%20%3a%20Week%2030&amp;body=%2fpost%2fweek_30%2ftidy-tuesday-week-30%2f">
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  </ul>
</div>


  

</div>

  
</div>



  <div class="article-container">

    <div class="article-style" itemprop="articleBody">
      <div id="movie-profit-generally" class="section level1">
<h1>Movie Profit Generally</h1>
</div>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>This is my second post on <a href="https://github.com/rfordatascience/tidytuesday">Tidy Tuesday</a> and the dataset in question is <a href="https://github.com/rfordatascience/tidytuesday/tree/master/data/2018-10-23">Movie profit</a> dataset.</p>
<pre class="r"><code># looking at dimensions
dim(Movie)</code></pre>
<pre><code>## [1] 3401    8</code></pre>
<pre class="r"><code># check for missing values in numerical values
attach(Movie)
summary(release_date)</code></pre>
<pre><code>##    Length     Class      Mode 
##      3401 character character</code></pre>
<pre class="r"><code>summary(production_budget)</code></pre>
<pre><code>##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
##    250000   9000000  20000000  33284743  45000000 175000000</code></pre>
<pre class="r"><code>summary(domestic_gross)</code></pre>
<pre><code>##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
##         0   6118683  25533818  45421793  60323786 474544677</code></pre>
<pre class="r"><code>summary(worldwide_gross)</code></pre>
<pre><code>##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## 0.000e+00 1.062e+07 4.016e+07 9.412e+07 1.176e+08 1.305e+09</code></pre>
<pre class="r"><code># checking factors or level of categorical variables
#summary.factor(distributor)   
length(summary.factor(distributor))</code></pre>
<pre><code>## [1] 202</code></pre>
<pre class="r"><code>summary.factor(mpaa_rating)</code></pre>
<pre><code>##     G    PG PG-13     R  NA&#39;s 
##    85   573  1092  1514   137</code></pre>
<pre class="r"><code>ggplot(Movie,aes(mpaa_rating))+theme_bw()+
  geom_bar()+geom_bar()+stat_count(aes(y=..count.., label=..count..), geom=&quot;text&quot;, vjust=-.5)</code></pre>
<p><img src="/post/2018-11-14-tidy-tuesday-week-30_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<pre class="r"><code>summary.factor(genre)</code></pre>
<pre><code>##    Action Adventure    Comedy     Drama    Horror 
##       573       481       813      1236       298</code></pre>
<pre class="r"><code>ggplot(Movie,aes(genre))+theme_bw()+
  geom_bar()+stat_count(aes(y=..count.., label=..count..), geom=&quot;text&quot;, vjust=-.5)</code></pre>
<p><img src="/post/2018-11-14-tidy-tuesday-week-30_files/figure-html/unnamed-chunk-1-2.png" width="672" /></p>
<pre class="r"><code># checking for bias in mpaa rating and genre 
table(mpaa_rating,genre)</code></pre>
<pre><code>##            genre
## mpaa_rating Action Adventure Comedy Drama Horror
##       G          1        67      6    11      0
##       PG        34       309     79   144      7
##       PG-13    225        83    328   398     58
##       R        286        14    367   645    202</code></pre>
<pre class="r"><code># column percentage for above table
table(mpaa_rating,genre) %&gt;%
prop.table(margin=2) %&gt;%
round(digits = 2)</code></pre>
<pre><code>##            genre
## mpaa_rating Action Adventure Comedy Drama Horror
##       G       0.00      0.14   0.01  0.01   0.00
##       PG      0.06      0.65   0.10  0.12   0.03
##       PG-13   0.41      0.18   0.42  0.33   0.22
##       R       0.52      0.03   0.47  0.54   0.76</code></pre>
<ol style="list-style-type: decimal">
<li>3401 movies with 8 variables of information which include numeric and categorical.</li>
<li>There are 202 distributors for movies of four types of ratings which are G, PG, PG-13 and R, but 137 movies have no record of them.</li>
<li>Also there are five categories for genre, where Drama with 1236, while horror with 298 movies.</li>
<li>There is only one action movie for general audiences(for all) and obviously no horror film should be watched by children alone, yet there are 7 movies which you can watch with your parents.</li>
<li>Comedy movies are mostly R rated(under 17 requires guardian) and PG-13 (some material is inappropriate to under 13). The frequencies are respectively 367 and 328.</li>
<li>Where 309 movies of adventure genre could be watched by children with accompanying parents and most(67) number of adventure movies can be watched by all ages. Yet 645 Drama movies are R-rated.</li>
<li>We think horror movies are mostly R-rated then it is true. But only is relative to percentage because considering the frequencies we make horror movies the least even according to this random sample.</li>
<li>This dataset contains the release dates from 1936 to 2019. Even though it is not 2019 there is a movie which has been listed here.</li>
<li>This explains the domestic and worldwide gross being zero as the minimum value of zero. Then again we have to be careful because there are movies which might not make profit at all.</li>
</ol>
<div id="lets-focus-of-movies-which-has-zero-domestic-gross" class="section level2">
<h2>Lets Focus of movies which has zero domestic gross</h2>
<pre><code>## [1] 66  8</code></pre>
<pre><code>##    Length     Class      Mode 
##        66 character character</code></pre>
<p><img src="/post/2018-11-14-tidy-tuesday-week-30_files/figure-html/graphical%20analysis%20for%20domestic%20gross%20zero%20movies-1.png" width="672" /></p>
<pre><code>## [1] 43</code></pre>
<pre><code>##    PG PG-13     R  NA&#39;s 
##    12    12    31    11</code></pre>
<pre><code>##    Action Adventure    Comedy     Drama    Horror 
##        14        10        10        24         8</code></pre>
<p><img src="/post/2018-11-14-tidy-tuesday-week-30_files/figure-html/graphical%20analysis%20for%20domestic%20gross%20zero%20movies-2.png" width="672" /></p>
<pre><code>## # A tibble: 9 x 8
##   release_date movie production_budg~ domestic_gross worldwide_gross
##   &lt;chr&gt;        &lt;chr&gt;            &lt;dbl&gt;          &lt;dbl&gt;           &lt;dbl&gt;
## 1 5/27/2011    Die ~          7250000              0        35122948
## 2 11/24/2006   Kurt~          8300000              0        24906717
## 3 5/4/2012     LOL           11000000              0        10431506
## 4 3/31/2004    The ~         20000000              0         5918742
## 5 7/8/2011     Iron~         25000000              0         5297411
## 6 2/24/2017    The ~          5250000              0         4802379
## 7 9/29/2017    Don ~          8000000              0         4598934
## 8 12/14/2007   Good~         30000000              0         2717302
## 9 9/9/2011     Grav~          2000000              0         2151887
## # ... with 3 more variables: distributor &lt;chr&gt;, mpaa_rating &lt;chr&gt;,
## #   genre &lt;chr&gt;</code></pre>
<p><img src="/post/2018-11-14-tidy-tuesday-week-30_files/figure-html/graphical%20analysis%20for%20domestic%20gross%20zero%20movies-3.png" width="672" /></p>
<pre><code>## # A tibble: 10 x 8
##    release_date movie production_budg~ domestic_gross worldwide_gross
##    &lt;chr&gt;        &lt;chr&gt;            &lt;dbl&gt;          &lt;dbl&gt;           &lt;dbl&gt;
##  1 3/31/2004    The ~         20000000              0         5918742
##  2 8/29/2014    Dweg~         20000000              0               0
##  3 7/8/2011     Iron~         25000000              0         5297411
##  4 3/17/2015    Acci~         26000000              0          135436
##  5 12/14/2007   Good~         30000000              0         2717302
##  6 3/13/2015    The ~         35000000              0           11106
##  7 4/14/2017    Quee~         36000000              0         1578543
##  8 11/11/2016   USS ~         40000000              0         1641255
##  9 3/15/2019    Wond~        100000000              0               0
## 10 12/21/2018   Aqua~        160000000              0               0
## # ... with 3 more variables: distributor &lt;chr&gt;, mpaa_rating &lt;chr&gt;,
## #   genre &lt;chr&gt;</code></pre>
<ol style="list-style-type: decimal">
<li><p>There are 66 movies which have not made domestic profit at all. Majority of movies(31) from R rated<br />
and 24 of them are Drama genre.</p></li>
<li><p>Even though no gross in domestic they have done quite done well around. There are 9 movies as outliers of this boxplot for genre. It should be noted that Drama category has the most significant outlier with 30 million where second outlier from action movie of close to 25 million dollars.</p></li>
</ol>
<p>If we focus on the production budget with genre there are 7 outliers and one action movie has spent more than 1.5 billion dollars from the action genre while a movie from adventure category spent almost 1 billion USD. others are less than 50 milion USD. According to the descending order in the last 10 movies with lowest production budget only 2 have profitted. One movie (All the Boys Love Mandy Lane) has considereably done good, but if you consider this list of 10 movies we have 12 angry men as well. This indicates that we didn’t have records how much of profit in home and away, because there is no way that people didn’t watch that movie.So we conclude that some movies even though they aired earlier in the century did not has to be recorded for domestic and worldwide profit.</p>
<pre class="r"><code>Movie_worldwide_zero&lt;-subset.data.frame(Movie,c(worldwide_gross==0))
attach(Movie_worldwide_zero)</code></pre>
<pre><code>## The following objects are masked from Movie_domestic_zero:
## 
##     distributor, domestic_gross, genre, movie, mpaa_rating,
##     production_budget, release_date, worldwide_gross</code></pre>
<pre><code>## The following objects are masked from Movie:
## 
##     distributor, domestic_gross, genre, movie, mpaa_rating,
##     production_budget, release_date, worldwide_gross</code></pre>
<pre class="r"><code># check for missing values in numerical values
summary(release_date)</code></pre>
<pre><code>##    Length     Class      Mode 
##        36 character character</code></pre>
<pre class="r"><code>summary(production_budget)</code></pre>
<pre><code>##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
##    340000   1200000   3500000  11965000   8925000 160000000</code></pre>
<pre class="r"><code>summary(domestic_gross)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##       0       0       0       0       0       0</code></pre>
<pre class="r"><code>summary(worldwide_gross)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##       0       0       0       0       0       0</code></pre>
<pre class="r"><code># checking factors or level of categorical variables
#summary.factor(distributor)
length(summary.factor(distributor))</code></pre>
<pre><code>## [1] 28</code></pre>
<pre class="r"><code>summary.factor(mpaa_rating)</code></pre>
<pre><code>##    PG PG-13     R  NA&#39;s 
##    10     5    16     5</code></pre>
<pre class="r"><code>summary.factor(genre)</code></pre>
<pre><code>##    Action Adventure    Comedy     Drama    Horror 
##         9         5         6        13         3</code></pre>
</div>
</div>

    </div>

    





    
    

    

    


  </div>
</article>

<div class="container">
  <footer class="site-footer">
  
  <p class="powered-by">
    <a href="/privacy/">Privacy Policy of MIT</a>
  </p>
  

  <p class="powered-by">
    &copy; 2018 &middot; 

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" id="back_to_top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

</div>


<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

    

    
    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha512-+NqPlbbtM1QqiK8ZAo4Yrj2c4lNQoGv8P79DPtKzj++l5jnN39rHA/xsqn8zE9l0uSoxaCdrOgFs6yjyfbBxSg==" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.3/imagesloaded.pkgd.min.js" integrity="sha512-umsR78NN0D23AzgoZ11K7raBD+R6hqKojyBZs1w8WvYlsI+QuKRGBx3LFCwhatzBunCjDuJpDHwxD13sLMbpRA==" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha256-VsEqElsCHSGmnmHXGQzvoWjWwoznFSZc6hs7ARLRacQ=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.4/isotope.pkgd.min.js" integrity="sha512-VDBOIlDbuC4VWxGJNmuFRQ0Li0SKkDpmGyuhAG5LTDLd/dJ/S0WMVxriR2Y+CyPL5gzjpN4f/6iqWVBJlht0tQ==" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" integrity="sha256-X5PoE3KU5l+JcX+w09p/wHl9AzK333C4hJ2I9S5mD4M=" crossorigin="anonymous"></script>

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js" integrity="sha256-/BfiIkHlHoVihZdc6TFuj7MmJ0TWcWsMXkeDFwhi0zw=" crossorigin="anonymous"></script>
        
        <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
        
        <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/python.min.js"></script>
        
      

      
      
    

    <script src="/js/hugo-academic.js"></script>
    

    
    

    
    
    

    
    
    <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script>
      const search_index_filename = "/index.json";
      const i18n = {
        'placeholder': "Search...",
        'results': "Search Results",
        'no_results': "No results found"
      };
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    <script src="/js/search.js"></script>
    

    
    

  </body>
</html>

