---
title: 'Week 20 : Global Plastic Waste'
author: M.Amalan
date: '2019-05-21'
slug: Week20
output:
    blogdown::html_document:
      toc: true
categories:
  - TidyTuesday
tags:
  - TidyTuesday
  - tidyverse
  - gganimate
image:
  caption: ''
  focal_point: ''
summary: '2019 Week 20 TidyTuesday: Plastic Waste Data'  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE,message = FALSE,fig.width = 12,fig.height = 12)
```

```{r Load the data and packages}
library(tidyverse)
library(readr)
library(gganimate)

coast_vs_waste <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/coastal-population-vs-mismanaged-plastic.csv")

mismanaged_vs_gdp <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/per-capita-mismanaged-plastic-waste-vs-gdp-per-capita.csv")

waste_vs_gdp <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/per-capita-plastic-waste-vs-gdp-per-capita.csv")
```

