---
title: Tree of Binomial Distribution
author: M.Amalan
date: '2019-02-14'
slug: BinomialDistribution
output:
  blogdown::html_page:
    toc: true
categories:
  - fitODBOD
  - Blog
  - Binomi
tags:
  - Beta-Binomial
  - fitODBOD
  - Binomial
image:
  caption: ''
  focal_point: ''
---

# Binomial Distribution

The binomial distribution can be defined, using the binomial expansion 

$$ (q+p)^n = \sum_{x=0}^{n} {n \choose k} p^k q^{(n-k)} = \sum_{x=0}^{n} \frac{n!} {k! (n-k)!} p^k q^{(n-k)}$$

as the distribution of a randm variable X for which 

$$Pr[X=x] = {n \choose k} p^k q^{(n-k)}$$ 

$x=0,1,2,...,n.$ where $q+p=1$, $p,q>0$ and $n$ is a positive integer. When $n=1$, the distribution is known as the 
Bernoulli distribution. The mean and variance are $\mu=np$ and  $\mu_2 = npq$.

If $n$ independent trials are made and in each there is probability $p$ that the outcome $E$ will occur, 
then the number of trials in which $E$ occurs can be represented by a random variable $X$ having the binomial distribution 
with parameters $n$, $p$. 

This situation occurs when a sample of ﬁxed size $n$ is taken from an inﬁnite population 
where each element in the population has an **"equal"** and **"independent"** probability $p$ of possession of a speciﬁed 
attribute. The situation also arises when a sample of ﬁxed size $n$ is taken from a ﬁnite population where each 
element in the population has an **"equal"** and **"independent"** probability $p$ of having a speciﬁed attribute 
and elements are sampled independently and sequentially with replacement. 

The distribution was derived by James Bernoulli (in his treatise Ars Conjectandi, published in 1713), 
for the case $p = r/(r+s)$, where $r$ and $s$ are positive integers.

The binomial distribution is of such importance in applied probability and statistics that it is frequently 
necessary to calculate probabilities based on this distribution. Although the calculation of sums of the form

$$ \sum_{x} {n \choose x} p^x q^{(n-x)}$$

is straightforward, it can be tedious, especially when n and x are large and when there are a large number of terms in 
the summation. It is not surprising that a great deal of attention and ingenuity have been applied to constructing 
useful approximations for sums of this kind. 

# Applications 

1. The binomial distribution arises whenever underlying events have two possible outcomes, the chances of which remain
constant. The importance of the distribution has extended from its original application in gaming to many other areas. 

2. Its use in genetics arises because the inheritance of biological characteristics depends on genes that occur in pairs;
see, for example, Fisher and Matheras (1936) analysis of data on straight versus wavy hair in mice.

3. More recent application in genetics is the study of the number of nucleotides that are in the same state in two 
DNA sequences (Kaplan and Risko, 1982). 

4. The number of defectives found in random samples of size n from a stable productionprocessisa binomial
variable;acceptancesampling isa veryimportant application of the test for the mean of a binomial sample against a
hypothetical value. 

5. Seber (1982b) has given a number of instances of the use of the binomial distribution in animal ecology, for example, 
in mark-recapture estimation of the size of an animal population. Boswell, Ord, and Patil (1979) gave applications in 
plant ecology. 

Although appealing in their simplicity, the assumptions of independence and constant probability for the binomial
distribution are not often precisely satisfied. Published critical appraisals of the extent of departure from these
assumptions in actual situations are rather rare.

# Binomial Mixture Distributions

The binomial distribution hastwoparameters, $n$ and $p$, and either or both of these may be supposed to have a probability
distribution. We will not discuss cases in which both $n$ and $p$ vary, though it is easy to construct such examples. 

In most cases discussed in the statistical literature, $p$ has a continuous distribution, while $n$ is discrete. The 
latter restriction is necessary, but the former is not.

However, discrete distributions for $p$ have not been found to be useful and have not attracted much attention from a
theoretical point of view. 

```{r Diagramme}
library(DiagrammeR)


```

