---
title: 'Week 26: Unidentified Flying Objects'
author: M.Amalan
date: '2019-06-24'
slug: Week26
output: 
    blogdown::html_page:
      toc: true
categories:
  - TidyTuesday
tags:
  - tidyverse
  - TidyTuesday
  - gganimate
image:
  caption: ''
  focal_point: ''
summary: '2019 Week 26 TidyTuesday: UFOs So Far.'    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE,message = FALSE,fig.width = 12,fig.height = 9)
```

```{r load the data and packages}
ufo_sightings <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-25/ufo_sightings.csv")

library(tidyverse)
library(gganimate)
library(ggthemes)
library(lubridate)
```

# Timely changes for country and shape

## Yearly count changes

```{r Yearly count}
ufo_sightings$date_time <- mdy_hm(ufo_sightings$date_time)

ufo_sightings %>%
  mutate(year=year(date_time)) %>%
  count(year) %>%
  ggplot(.,aes(x=as.factor(year),y=n))+geom_col(fill=blues9[4])+
         theme_minimal()+
         theme(axis.text.x = element_text(angle = 90))+
         geom_text(aes(label=n),hjust=-0.1,angle=90,color=blues9[9])+
         xlab("Years")+ylab("Frequency")+
         ggtitle("Yearly count changes")
```

## Monthly count changes

```{r Monthly count}
ufo_sightings %>%
  mutate(month=month(date_time)) %>%
  count(month) %>%
  ggplot(.,aes(x=as.factor(month),y=n))+geom_col(fill=blues9[4])+
         theme_minimal()+
         geom_text(aes(label=n),vjust=-0.1,color=blues9[9])+
         xlab("Months")+ylab("Frequency")+
         ggtitle("Monthly count changes")
```

## Yearly Count changes for Countries

```{r Yearly but countries}
ufo_sightings %>%
   mutate(year=year(date_time)) %>%
   mutate(country=recode_factor(country,
                                "au"="Australia",
                                "ca"="Canada",
                                "gb"="Great Britain",
                                "us"="USA")) %>%
   group_by(year,country) %>%
   remove_missing() %>%
   count(country) %>%
   ggplot(.,aes(x=as.factor(year),y=n))+geom_col(fill=blues9[8])+
         theme_minimal()+
         facet_wrap(~country,scales = "free_y",ncol = 1)+
         theme(axis.text.x = element_text(angle = 90))+
         xlab("Year")+ylab("Frequency")+
         ggtitle("Yearly count changes for Nations")
      
```

## Monthly Count changes for Countries

```{r Monthly but countries}
ufo_sightings %>%
   mutate(month=month(date_time)) %>%
   mutate(country=recode_factor(country,
                                "au"="Australia",
                                "ca"="Canada",
                                "gb"="Great Britain",
                                "us"="USA")) %>%
   group_by(month,country) %>%
   remove_missing() %>%
   count(country) %>%
   ggplot(.,aes(x=as.factor(month),y=n))+geom_col(fill=blues9[8])+
         theme_minimal()+
         facet_wrap(~country,scales = "free_y",ncol = 1)+
         geom_text(aes(label=n),vjust=0.95,color="white")+
         xlab("Months")+ylab("Frequency")+
         ggtitle("Monthly count changes for Nations")
      
```

## Decade wise UFO shape changes

```{r Yearly shapes but decades}
ufo_sightings_new<-ufo_sightings

ufo_sightings_new$year<-year(ufo_sightings_new$date_time)

ufo_sightings_new$year<-cut(ufo_sightings_new$year,
                            breaks=c(1910,1919,1929,1939,
                                     1949,1959,1969,1979,
                                     1989,1999,2009,2015),
                            labels=c("1910s","1920s","1930s","1940s",
                                     "1950s","1960s","1970s","1980s",
                                     "1990s","2000s","2010s"))

ufo_sightings_new %>%
  group_by(year,ufo_shape) %>%
  count(ufo_shape) %>%
  remove_missing() %>%
  ggplot(.,aes(x=str_wrap(ufo_shape,10),y=n))+geom_col(fill=blues9[8])+
         theme_minimal()+
         theme(axis.text.x = element_text(angle = 90))+
         geom_text(aes(label=n),hjust=-0.1,angle=90)+
         scale_y_continuous(expand = c(0,1000))+
         transition_states(year)+ease_aes("linear")+
         xlab("Shape")+ylab("Frequency")+
         ggtitle("UFO shapes over the Years",
                 subtitle = "Year:{closest_state}")

```


