---
title: 'Sri Lanka and its affect on/in Journal Articles '
author: M.Amalan
date: '2019-02-18'
slug: SLandJournal
output:
    blogdown::html_page:
      toc : true
categories:
  - Blog
  - R
  - SL
  - Journal
tags:
  - gganimate
  - tidyverse
  - R package
  - R
  - SL
image:
  caption: ''
  focal_point: ''
summary: "Exploring How has Sri Lanka done in related to Academic Journals."
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE,warning = FALSE,fig.width = 10,fig.height = 10)
```

# Introduction


# Packages and Ideas

```{r Packages and data}
# Data
library(sjrdata)

# Packages
library(tidyverse)
library(gganimate)
library(ggrepel)
library(magrittr)
library(lubridate)
library(ggthemr)
ggthemr("flat dark")
```

# Ranking of Sri Lanka from 1996 to 2017

```{r sjr Sri Lanka and rank}
subset(sjr_countries,country=="Sri Lanka") %>%
  mutate(year=year(as.Date(year,"%Y"))) %>%
ggplot(.,aes(x=year,y=rank,label=rank))+
  geom_point()+geom_line()+
  geom_text_repel()+
  xlab("Year")+ylab("Rank")+
  ggtitle("Rank of Sri Lanka Changing from 1996 to 2017")+
  theme(axis.text.x =element_text(angle = 90, hjust = 1))
```

# Documents , Citable Documents and Self Citations from Sri Lanka Journals from 1996 to 2017

```{r sjr Sri Lanka and documents citable documents self citations}
sjr_countries%>%
  gather(citing,values,"documents","citable_documents","self_citations") %>%
  subset(country=="Sri Lanka",select=c(citing,values,year)) %>%
  mutate(year=year(as.Date(year,"%Y"))) %>%
ggplot(.,aes(x=year,y=values,label=values,color=citing,shape=citing))+
  geom_point()+geom_line()+
  geom_text_repel()+
  xlab("Year")+ylab("Counts")+
  scale_x_continuous(breaks=seq(1996,2017),labels=seq(1996,2017))+
  scale_y_continuous(breaks=seq(0,2000,100),labels=seq(0,2000,100))+
  ggtitle("Document Counts Changing from 1996 to 2017 for Sri Lanka")+
  theme(axis.text.x =element_text(angle = 90, hjust = 1))
```

# Citations per Document from Sri Lankan Journals

```{r sjr citations per document}
sjr_countries %>%
   subset(country=="Sri Lanka") %>%
   mutate(year=year(as.Date(year,"%Y"))) %>%
ggplot(.,aes(x=year,y=citations_per_document,
          label=citations_per_document))+
  geom_point()+geom_line()+
  geom_text_repel()+
  xlab("Year")+ylab("Citations Per Document")+
  scale_x_continuous(breaks=seq(1996,2017),labels=seq(1996,2017))+
  scale_y_continuous(breaks=seq(0,30),labels=seq(0,30))+
  ggtitle("Citations Per Document from 1996 to 2017 for Sri Lanka")+
  theme(axis.text.x =element_text(angle = 90, hjust = 1))
```

