---
title: Developing an R package
author: M.Amalan
date: '2019-01-10'
output:
  blogdown::html_page:
    toc: true
slug: developing-an-r-package
categories:
  - fitODBOD
  - R
tags:
  - R
  - R package
  - fitODBOD
image:
  caption: ''
  focal_point: ''
---

# Introduction

R package development is no longer as it was before 2010 because now most of the work can be done by
just a simple mouse-click or with the use of a function. My intention of writing this blog post is not to 
give a thorough demonstration of how to develop your own R package. But it will briefly explain the 
process with the most important steps, and will include valuable blog posts and websites which helped me
to develop my own R package [fitODBOD.](https://cran.r-project.org/package=fitODBOD)

# Credit
  
  I would definitely recommend to read all of these books and start your package development. Or
  at least make step by step progress in your work while reading them. If you have a basic knowledge 
  regarding R, R studio, CRAN and writing programs, they are more than enough for you to start.
  
* [R packages by Hadley Wickam](http://r-pkgs.had.co.nz/)

  This website contains everything that is in the book. The basic things related to an R
  package development process are structured properly here. It is very useful to read this 
  book/website. The package structure, the type of files necessary, how should the writing be
  in these files and further, what kind of ways can we use to achieve the final outputs. 
  The book is mainly focused on producing an R package which can be updated with the highest 
  standards using reproducing ability. Such as CRAN standards and GitHub releases. 
  
* [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html)

  Everything related to package development is included here with clear instructions.
  This document is provided by the CRAN project to make package development more friendlier.
  It includes the official standards for files and naming conventions related to R package 
  development. 
  
* [Creating R packages: A Tutorial by Friedrich Leish](https://cran.r-project.org/doc/contrib/Leisch-CreatingPackages.pdf) 

  A brief article explaining about writing functions, classes and methods for R package development. 
  This is very abstract and useful in package development specially as it is focusing on object oriented
  programming and S formulas. 
  
* [R for Beginners by Emmanuel Paradis](https://cran.r-project.org/doc/contrib/Paradis-rdebuts_en.pdf)

  A book explaining R and its ability in detail, for example regarding functions, data, abilities and 
  limitations of R. There is also a section for R packages, which has valuable information. Writing functions
  is very crucial in R package development therefore going through this document is worth. Several packages
  also include data-sets in them. While you develop functions similarly we can develop data-sets as well. There 
  are sections which includes information regarding data-sets as well.
  
* [The Art of R Programming by Norman Matloff](http://diytranscriptomics.com/Reading/files/The%20Art%20of%20R%20Programming.pdf)
  
  Another book that will be useful in understanding how R functions and data-sets can be used in R package
  development. 
  
* [The R Inferno by Patrick Burns](https://www.burns-stat.com/pages/Tutor/R_inferno.pdf) 

  Useful book related to object oriented programming, functions and data objects related to R. Very thorough and 
  scrutinized information with valuable explanation which makes things more clearer. 
  
```{r Drawng Diagramme,echo=FALSE}
library(DiagrammeR)

DiagrammeR(
           "graph TB;
           A(Code with Standards and comment)-->C(Create R package);
           C-->D(R package <br> Structure);
           D-->E(DESCRIPTION file);
           D-->F(README file);
           D-->G(/R directory);
           D-->H(/data directory);
           D-->I(/tests directory);
           D-->J(/man directory);
           D-->K(NAMESPACE file);
           D-->L(/vignettes <br> directory);
           D-->M(NEWS.md file);
           E-->O(Build <br> the package);
           O-->N(Source,Bundle,Binary,Installed,In Memory);
           F-->O;
           G-->O;
           H-->O; 
           I-->O;
           J-->O; 
           K-->O; 
           L-->O;
           M-->O;
           "
          )
```
# 1) Coding Standards or Coding to Understand

# 2) Package Structure

# 3) DESCRIPTION file

# 4) README file

# 5) /R directory

# 6) /data directory

# 7) /tests directory

# 8) /man directory

# 9) NAMSESPACE file

# 10) Vignette.pdf

# Manual.pdf

# Building the Package

# Testing and checking the Package

# Distributing the Package
